version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: mydb

    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
